# Quick Notes

In [1]:
# plots pictures here instead of a new window
# any updates to libraries get automatically
%matplotlib inline
%reload_ext autoreload
%autoreload 2

# check regular expressions  RegEx = r’/([^/]+)_\d+.jpg$’ => gets section of a string
# to see argument details of a function => shift + tab
# help on command-> command??
# Pi torch - any function ends with _ means return values replace e.g. x[:,0].uniform_(-1,1)
# rank x tensor(array)-> x shows dimension e.g. pictures are saved rank 3 tensors, column, row, and channels
# comment multiple lines, select lines then control+slash (/)
# __X__ -> Dunder (double underscore) or magic methods

# Quicksort Algorithm

In [2]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    print(left)
    print(middle)
    print(right)
    print("loop number = X")
    return quicksort(left) + middle + quicksort(right)

print('\r\nResult = ', quicksort([3,6,8,10,11,1,2,1]))

[3, 6, 8, 10, 1, 2, 1]
[11]
[]
loop number = X
[3, 6, 8, 1, 2, 1]
[10]
[]
loop number = X
[]
[1, 1]
[3, 6, 8, 2]
loop number = X
[3, 6, 2]
[8]
[]
loop number = X
[3, 2]
[6]
[]
loop number = X
[]
[2]
[3]
loop number = X

Result =  [1, 1, 2, 3, 6, 8, 10, 11]


## Environment

### C which environment currently used

In [3]:
import sys
print(sys.prefix)

/Users/olgu/opt/anaconda3


### c what is installed - ! enables python to run cmd line commands

In [4]:
!python3 -m pip freeze

attrs==18.2.0
pdflatex==0.1.3


### to upgrade a package

In [5]:
import sys
!{sys.executable} -m pip install --upgrade pip

### to install a package

In [6]:
import sys
!{sys.executable} -m pip install numpy

## Import

In [7]:
from numpy import dot # instead of import numpy as np, then np.dot. Also, we do not load the whole lib, only the ones we need
a=list(range(4))
b=dot(a,2)
print(b)

[0 2 4 6]


# List

In [8]:
x1=list(range(5))
x2=[2]*5
a=[3,6,8,10,11,1,2,1]
print(x1)
print(x2)
print(a[:4])
print(a[4:])
print(a[3])
print(a[-1])

[0, 1, 2, 3, 4]
[2, 2, 2, 2, 2]
[3, 6, 8, 10]
[11, 1, 2, 1]
10
1


### A list of lists and NOT a 2D array. a.shape does not work. Would work in numpy seen below

In [9]:
a = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
print(f"size of the list = {len(a)}")
print(f"size of the first element of the list = {len(a[0])}")

size of the list = 3
size of the first element of the list = 4


# numpy array (not python list)

In [10]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(type(a))
print(a[:2, 1:3])
print(a.shape)

<class 'numpy.ndarray'>
[[2 3]
 [6 7]]
(3, 4)


# Other differences numpy array vs python list

### python list needs np.dot for multiplication

In [11]:
a=[1,2,3]
da=a*2
print('da='+str(da))
a2=np.dot(a,2)
print('a2='+str(a2))

da=[1, 2, 3, 1, 2, 3]
a2=[2 4 6]


### numpy array does NOT need np.dot for multiplication

In [12]:
na=np.array(a)
print('na='+str(na))
na2=na*2
print('na2='+str(na2))

na=[1 2 3]
na2=[2 4 6]


### make a column vector

In [13]:
cv = np.array([1,2,3])
cv.shape=(3,1)
cv
cv@cv.T

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

### text and print variables

In [14]:
#Internally, repr()function calls __repr__() of the given object.
#You can easily implement/override __repr__() so that repr() works differently.
class Person:
    name = 'Adam'

class Person_repr:
    name = 'Adam'

    def __str__(self):
        return 'My str'
    def __repr__(self):
        return repr('Hello ' + self.name )

without_repr = f"without repr override => {repr(Person())}"
with_repr = f"with repr override => {repr(Person_repr())}"
with_format = '{0!s} {0!r}'.format(Person_repr())
print(without_repr)
print(with_repr)
print(with_format)

without repr override => <__main__.Person object at 0x7fb5eb78a2d0>
with repr override => 'Hello Adam'
My str 'Hello Adam'


### To print more than one var, print them as tuple a,b,c. No need for paranthesis (a,b,c)

In [15]:
with_repr, without_repr, with_format

("with repr override => 'Hello Adam'",
 'without repr override => <__main__.Person object at 0x7fb5eb78a2d0>',
 "My str 'Hello Adam'")

### vs this would print only the last one

In [16]:
with_repr
without_repr
with_format

"My str 'Hello Adam'"

In [17]:
d = {'cat': 'cute', 'dog': 'furry'}
idx=1
animal="monkey"
print('{1} #{0}'.format(idx, animal)) # note the order. Not {0} {1}
print('#%d: %s' % (idx, animal))
print(f'#{idx}: {animal}')
print(f"{d['cat']}")  # ok, quotations needs to be different
print(f'{d["cat"]}')  # ok, quotations needs to be different
#print(f"{d1["cat"]}") # NOT ok. Cannot use the same quotation

monkey #1
#1: monkey
#1: monkey
cute
cute


In [18]:
s1='big'
s2='hello'
v1=10
print('This is a\r\n%s %s \r\nfrom number %d' % (s1.capitalize(), s2.upper(),v1))
print('\r\nThis is the number =',v1,'in the middle')
print(f"v1 = {v1}")

This is a
Big HELLO 
from number 10

This is the number = 10 in the middle
v1 = 10


### text list

In [19]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx, animal))  # or  print(f'#{idx}: {animal}')

#0: cat
#1: dog
#2: monkey


In [20]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


In [21]:
animals = ['cat', 'dog', 'monkey']
for animal in enumerate(animals):
    print(animal)

(0, 'cat')
(1, 'dog')
(2, 'monkey')


### Functions

In [22]:
def my_list(x:str="default", y:int=2)->list:
    """Explanation of function."""
    a=list(range(y))
    return a
def my_dict(x:str="default", y:int=2)->dict:
    a={}
    a["default"]=2
    return a
def my_no_return(x:str="default", y:int=2)->None:
    print("no return")

print(my_list())
print(my_dict())
my_no_return()
print("--- below prints 'no return' from fun call and 'None' for print statement")
print(my_no_return()) # note here that print returns None

[0, 1]
{'default': 2}
no return
--- below prints 'no return' from fun call and 'None' for print statement
no return
None


### List Comprehension

In [23]:
class Data(object):
    def __init__(self, name:str=""):
        self.name = name
        self.temp_name = "temp"
def my_fun(x:int=1)->None:
    return x+1
myds=[]
myds.append(Data("test"))
myds.append(Data(""))
myds.append(Data("all"))
a=list(range(5))
b=[my_fun(x) for x in a if x>2]
print(b)
c=[myd.name if myd.name else myd.temp_name for myd in myds]
print(c)
d=[myd.name if myd.name else myd.temp_name for myd in myds if myd.name!=""]
print(d)
e=[myd.name if myd.name else myd.temp_name for myd in myds if len(myd.name)>3]
print(e)

[4, 5]
['test', 'temp', 'all']
['test', 'all']
['test']


### Tuple

In [24]:
points = [(1,2)]
points.append((3,4))
b=[(x,y) for x,y in points if x>1]
print(b)
c=[x+y for x,y in points]
print(c)

[(3, 4)]
[3, 7]


### set (only unique element, NO duplicates)

In [25]:
data="3","a","4","b","a"  # tuple, NO need for paranthesis
chars = list(set(data))   # "a" is duplicate.
print(data)
print(chars) # chars has only one "a"
print(enumerate(chars))

('3', 'a', '4', 'b', 'a')
['a', '3', 'b', '4']


### Dictionary, NO duplicate key (make keys of dict a set)

In [26]:
d = {"cat": "cute", "dog": "furry"}  # Create a new dictionary with some data
d["fish"] = "wet"
print(d)

{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}


In [27]:
if 'cat' in d:  # OR, if 'cat' in d.keys():
    print(f'cat is a key in the dict with value = {d["cat"]}') # note the single quotation

cat is a key in the dict with value = cute


In [28]:
for key, value in d.items():
    print(f"{key} , {value}")

cat , cute
dog , furry
fish , wet


### create a dict via lambda (not complete)

In [29]:
act={'relu': lambda x:np.maximum(0,x), 'tanh': lambda x:np.tanh(x)}
act

{'relu': <function __main__.<lambda>(x)>,
 'tanh': <function __main__.<lambda>(x)>}

### create a dict via enumerate

In [30]:
data="3","a","4","b","a"
data="a","b","c","d"
sdata=set(data)
chars = list(set(data))                             # chars is a list of unique chars ['u', 'r', 'm', 'h', 'y', 'N', 'R', 't', '.', ' ', 'l', 'd', 'e', 'T', ...]
char_to_ix = { ch:i for i,ch in enumerate(chars) }  # char_to_ix is a dictionary {' ': 9, '.': 8, 'I': 16, 'N': 5, 'R': 6, 'T': 13, 'a': 21, 'b': 22, 'c': 14, 'd': 11, 'e': 12, 'f': 19, 'g': 25, 'h': 3, ...}
ix_to_char = { i:ch for i,ch in enumerate(chars) }  # ix_to_char is a dictionary {0: 'u', 1: 'r', 2: 'm', 3: 'h', 4: 'y', 5: 'N', 6: 'R', 7: 't', 8: '.', 9: ' ', 10: 'l', 11: 'd', 12: 'e', 13: 'T', ...}
char_to_ix, ix_to_char

({'c': 0, 'a': 1, 'd': 2, 'b': 3}, {0: 'c', 1: 'a', 2: 'd', 3: 'b'})

In [31]:
data

('a', 'b', 'c', 'd')

In [32]:
sdata

{'a', 'b', 'c', 'd'}

In [33]:
chars

['c', 'a', 'd', 'b']

### Saving and Loading

In [34]:
# Creating the type of a structure
dtype = [('Name', (np.str_, 10)), ('Marks', np.float64), ('GradeLevel', np.int32)]
#Creating a Strucured Numpy array
structuredArr = np.array([('Sam', 33.3, 3), ('Mike', 44.4, 5), ('Aadi', 66.6, 6), ('Riti', 88.8, 7)], dtype=dtype)
np.savetxt('struct_array.csv', structuredArr, delimiter=',', fmt=['%s' , '%f', '%d'], header='Name,Marks,Age', comments='')

In [35]:
from os import getcwd
print(getcwd())
# as csv
data=np.arange(0,10,1)
# data=np.array(['this', 'is', 'Olgu'])
np.savetxt('data.csv',[data],delimiter=',')
data_csv = np.loadtxt('data.csv', delimiter=',')

# as binary *.npy file
np.save('data.npy', data)
data_bin = np.load('data.npy')

# as compressed *.npz file. When loading, it loads in dict with names ‘arr_0’ for the first array, ‘arr_1’ for the second, and so on.
np.savez_compressed('data.npz', data)
dict_data = np.load('data.npz')
data_comp = dict_data['arr_0']

/Users/olgu/Documents/Olgu/Study/Coding/Python


In [36]:
data_comp

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Classes

In [37]:
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')
g.greet()
g.greet(loud=True)

Hello, Fred
HELLO, FRED!


In [38]:
class Person:
  def __init__(mysillyobject, name, age):
    mysillyobject.name = name
    mysillyobject.age = age

  def myfunc(abc):
    print("Hello my name is = %s woooww" % abc.age)

p1 = Person("John", 36)
p1.myfunc()

Hello my name is = 36 woooww


In [39]:
from random import randint
for i in range(3):
    print(randint(1, 25))

14
17
19


In [40]:
from re import findall as fa
test='this is a test'
mod=r'.'
test_re = fa(mod,test)
test_re

['t', 'h', 'i', 's', ' ', 'i', 's', ' ', 'a', ' ', 't', 'e', 's', 't']

In [41]:
len?

In [42]:
xa=list(range(5))
ya=np.dot(xa,2)
aa,bb,n=[],[],[]
min_bound = np.int32(len(xa) * .0)
max_bound = np.int32(len(xa) * 1)
for i in range(min_bound,max_bound+1):
  xm1 = np.hstack([xa[:i], np.zeros(len(xa)-i)])
  xm2 = np.hstack([np.zeros(i), xa[i:]])
  xm = np.vstack([xm1, xm2]).T
  m, c = np.linalg.lstsq(xm, ya, rcond=None)[0]
  n.append(np.linalg.norm(ya-xm@np.hstack([m,c])))
  aa.append(m)
  bb.append(c)
aa, bb

([0.0, 0.0, 1.9999999999999998, 1.9999999999999998, 2.0000000000000004, 2.0],
 [1.9999999999999998, 1.9999999999999998, 2.0, 2.0, 2.0, 0.0])